from sqlalchemy import Boolean, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from datetime import datetime

from app.db import Base


class ScanRunORM(Base):
    __tablename__ = "scan_runs"

    run_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    market_status: Mapped[str] = mapped_column(String(16), index=True)
    scan_count: Mapped[int] = mapped_column(Integer)
    watchlist_size: Mapped[int] = mapped_column(Integer)
    alerts_sent: Mapped[int] = mapped_column(Integer, default=0)
    fear_greed_value: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fear_greed_label: Mapped[str | None] = mapped_column(String(32), nullable=True)


class ScanResultORM(Base):
    __tablename__ = "scan_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String(64), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    ticker: Mapped[str] = mapped_column(String(16), index=True)
    asset_type: Mapped[str] = mapped_column(String(16), default="stock", index=True)
    score: Mapped[float] = mapped_column(Float)
    calibrated_confidence: Mapped[float] = mapped_column(Float, default=0.0)
    calibration_source: Mapped[str] = mapped_column(String(16), default="raw")
    buy_score: Mapped[float] = mapped_column(Float, default=0.0)
    sell_score: Mapped[float] = mapped_column(Float, default=0.0)
    decision_signal: Mapped[str] = mapped_column(String(16), default="HOLD", index=True)
    scoring_version: Mapped[str] = mapped_column(String(32), default="v2-directional")
    explanation: Mapped[str] = mapped_column(Text)
    price: Mapped[float] = mapped_column(Float)
    price_change_pct: Mapped[float] = mapped_column(Float)
    relative_volume: Mapped[float] = mapped_column(Float)
    sentiment_score: Mapped[float] = mapped_column(Float)
    filing_flag: Mapped[bool] = mapped_column(Boolean, default=False)
    breakout_flag: Mapped[bool] = mapped_column(Boolean, default=False)
    market_status: Mapped[str] = mapped_column(String(16), index=True)
    sector_strength_score: Mapped[float] = mapped_column(Float, default=0.0)
    relative_strength_pct: Mapped[float] = mapped_column(Float, default=0.0)
    options_flow_score: Mapped[float] = mapped_column(Float, default=0.0)
    options_flow_summary: Mapped[str] = mapped_column(Text, default="No options signal.")
    options_flow_bullish: Mapped[bool] = mapped_column(Boolean, default=False)
    options_call_put_ratio: Mapped[float] = mapped_column(Float, default=0.0)
    alert_sent: Mapped[bool] = mapped_column(Boolean, default=False)

    news_checked: Mapped[bool] = mapped_column(Boolean, default=False)
    news_source: Mapped[str] = mapped_column(String(32), default="none")
    news_cache_label: Mapped[str | None] = mapped_column(Text, nullable=True)
    signal_label: Mapped[str] = mapped_column(String(16), default="weak")
    data_quality: Mapped[str] = mapped_column(String(16), default="ok")
    volatility_regime: Mapped[str] = mapped_column(String(16), default="normal")
    benchmark_ticker: Mapped[str | None] = mapped_column(String(16), nullable=True)
    benchmark_change_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    gate_passed: Mapped[bool] = mapped_column(Boolean, default=False)
    gate_reason: Mapped[str] = mapped_column(Text, default="Signal gate not evaluated.")
    gate_checks_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    coingecko_price_change_pct_24h: Mapped[float | None] = mapped_column(Float, nullable=True)
    coingecko_market_cap_rank: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fear_greed_value: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fear_greed_label: Mapped[str | None] = mapped_column(String(32), nullable=True)
    provider_status: Mapped[str] = mapped_column(String(16), default="ok")
    provider_warnings_json: Mapped[str | None] = mapped_column(Text, nullable=True)


class SignalOutcomeORM(Base):
    __tablename__ = "signal_outcomes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String(64), index=True)
    ticker: Mapped[str] = mapped_column(String(16), index=True)
    asset_type: Mapped[str] = mapped_column(String(16), default="stock", index=True)
    signal: Mapped[str] = mapped_column(String(16), index=True)
    confidence: Mapped[float] = mapped_column(Float)
    calibrated_confidence: Mapped[float] = mapped_column(Float, default=0.0)
    calibration_source: Mapped[str] = mapped_column(String(16), default="raw")
    raw_score: Mapped[float] = mapped_column(Float, default=0.0)
    score_band: Mapped[str] = mapped_column(String(16), default="0-59", index=True)
    scoring_version: Mapped[str] = mapped_column(String(32), default="v2-directional")
    market_status: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    buy_score: Mapped[float] = mapped_column(Float, default=0.0)
    sell_score: Mapped[float] = mapped_column(Float, default=0.0)
    signal_label: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    gate_passed: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    gate_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    news_source: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    relative_volume: Mapped[float | None] = mapped_column(Float, nullable=True)
    price_change_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    relative_strength_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    options_flow_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    options_flow_bullish: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    volatility_regime: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    data_quality: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    benchmark_change_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    entry_price: Mapped[float] = mapped_column(Float)
    generated_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    price_after_15m: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_after_15m: Mapped[float | None] = mapped_column(Float, nullable=True)
    evaluated_at_15m: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    status_15m: Mapped[str] = mapped_column(String(16), default="pending")
    price_after_1h: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_after_1h: Mapped[float | None] = mapped_column(Float, nullable=True)
    evaluated_at_1h: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    status_1h: Mapped[str] = mapped_column(String(16), default="pending")
    price_after_1d: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_after_1d: Mapped[float | None] = mapped_column(Float, nullable=True)
    evaluated_at_1d: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    status_1d: Mapped[str] = mapped_column(String(16), default="pending")


class ExecutionAuditORM(Base):
    __tablename__ = "execution_audits"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    ticker: Mapped[str] = mapped_column(String(16), index=True)
    asset_type: Mapped[str] = mapped_column(String(16), default="stock", index=True)
    side: Mapped[str] = mapped_column(String(16), index=True)
    order_type: Mapped[str] = mapped_column(String(16))
    qty: Mapped[float] = mapped_column(Float)
    dry_run: Mapped[bool] = mapped_column(Boolean, default=False)
    idempotency_key: Mapped[str | None] = mapped_column(String(128), nullable=True, index=True)
    lifecycle_status: Mapped[str] = mapped_column(String(32), default="previewed", index=True)
    latest_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    notional_estimate: Mapped[float | None] = mapped_column(Float, nullable=True)
    signal_run_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    signal_generated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True, index=True)
    latest_signal: Mapped[str | None] = mapped_column(String(16), nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    trade_gate_allowed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    trade_gate_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    submitted: Mapped[bool] = mapped_column(Boolean, default=False)
    broker_order_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    broker_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    preview_payload: Mapped[str] = mapped_column(Text, default="{}")
    request_payload: Mapped[str | None] = mapped_column(Text, nullable=True)
    broker_payload: Mapped[str | None] = mapped_column(Text, nullable=True)
